version: '3.8'

services:
  codserver:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - codserver-network

  # MongoDB (opcional)
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - codserver-network
    profiles:
      - database

  # Redis (opcional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - codserver-network
    profiles:
      - cache

volumes:
  mongodb_data:
  redis_data:

networks:
  codserver-network:
    driver: bridge
